# Generated by Django 5.0.2 on 2024-02-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('team_leader', models.CharField(max_length=250)),
                ('desc', models.TextField()),
            ],
        ),
    ]
