# Generated by Django 5.0.2 on 2024-02-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name_plural': 'Teams'},
        ),
    ]
